# Generated by Django 5.2.14 on 2026-05-29 16:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0006_alter_clase_ciclo_lectivo'),
        ('students', '0003_remove_student_tipo_materia'),
        ('subjects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbral_nota_alerta', models.DecimalField(decimal_places=2, default=6.0, help_text='Nota por debajo de la cual se genera alerta (ej: 6.00)', max_digits=4)),
                ('umbral_inasistencia_pct', models.DecimalField(decimal_places=2, default=20.0, help_text='Porcentaje de inasistencias para generar alerta (ej: 20.00)', max_digits=5)),
                ('analisis_activo', models.BooleanField(default=True)),
                ('notificar_docentes', models.BooleanField(default=True)),
                ('notificar_representantes', models.BooleanField(default=True)),
                ('ciclo_lectivo_activo', models.CharField(blank=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Agente',
            },
        ),
        migrations.CreateModel(
            name='AlertaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CALIFICACION_BAJA', 'Calificación baja'), ('INASISTENCIA', 'Alta inasistencia'), ('TENDENCIA_NEGATIVA', 'Tendencia negativa'), ('MULTIPLES_MATERIAS', 'Bajo rendimiento en múltiples materias')], max_length=30)),
                ('severidad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10)),
                ('estado', models.CharField(choices=[('NUEVA', 'Nueva'), ('VISTA', 'Vista por docente'), ('NOTIFICADA', 'Notificado representante'), ('RESUELTA', 'Resuelta')], default='NUEVA', max_length=15)),
                ('promedio_detectado', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('porcentaje_inasistencia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('analisis_ia', models.TextField(help_text='Análisis detallado generado por el agente')),
                ('recomendaciones_ia', models.TextField(blank=True)),
                ('mensaje_docente', models.TextField(blank=True, help_text='Mensaje sugerido para el docente')),
                ('mensaje_representante', models.TextField(blank=True, help_text='Mensaje sugerido para el representante')),
                ('email_docente_enviado', models.BooleanField(default=False)),
                ('email_representante_enviado', models.BooleanField(default=False)),
                ('fecha_notificacion', models.DateTimeField(blank=True, null=True)),
                ('ciclo_lectivo', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_ia', to='students.student')),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Alerta de Estudiante',
                'verbose_name_plural': 'Alertas de Estudiantes',
                'ordering': ['-severidad', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InformeAsistido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_original', models.TextField()),
                ('texto_mejorado', models.TextField()),
                ('sugerencias_ia', models.TextField(blank=True, help_text='Lista de mejoras realizadas')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador IA'), ('ACEPTADO', 'Aceptado por docente'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informe_asistido', to='classes.activity')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_asistidos', to='users.usuario')),
            ],
            options={
                'verbose_name': 'Informe Asistido por IA',
                'verbose_name_plural': 'Informes Asistidos por IA',
                'ordering': ['-created_at'],
            },
        ),
    ]
