# Generated by Django 5.2.15 on 2026-06-30 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_tipo_materia'),
        ('users', '0002_alter_usuario_rol_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='representante_usuario',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'REPRESENTANTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='users.usuario', verbose_name='Usuario Representante'),
        ),
    ]
