# Generated by Django 5.2.9 on 2025-12-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('DOCENTE', 'Docente'), ('ESTUDIANTE', 'Estudiante'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=20),
        ),
    ]
