# Generated by Django 5.2.6 on 2025-10-15 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('grade', models.CharField(choices=[('2do Básica', '2do Básica'), ('3ro Básica', '3ro Básica'), ('4to Básica', '4to Básica'), ('5to Básica', '5to Básica'), ('6to Básica', '6to Básica'), ('7mo Básica', '7mo Básica'), ('8vo Básica', '8vo Básica'), ('1ro Bachillerato', '1ro Bachillerato'), ('2do Bachillerato', '2do Bachillerato'), ('3ro Bachillerato', '3ro Bachillerato')], max_length=50, verbose_name='Año escolar')),
                ('parent_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del padre/madre')),
                ('parent_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del padre/madre')),
                ('parent_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del padre/madre')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='teachers.teacher', verbose_name='Docente')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del estudiante')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['name'],
            },
        ),
    ]
