# Generated by Django 5.2.9 on 2025-12-20 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('teachers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del padre/madre')),
                ('parent_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del padre/madre')),
                ('parent_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del padre/madre')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/students/', verbose_name='Foto de perfil')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('registration_code', models.CharField(blank=True, max_length=36, null=True, unique=True, verbose_name='Código de Registro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grade_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classes.gradelevel', verbose_name='Grado')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='teachers.teacher', verbose_name='Docente')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to='users.usuario', verbose_name='Usuario unificado')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['usuario__nombre'],
            },
        ),
    ]
