# Generated by Django 5.2.9 on 2025-12-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tipo_materia',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tipo de Materia'),
        ),
    ]
