# Generated by Django 5.2.7 on 2025-10-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(max_length=50, verbose_name='Año escolar'),
        ),
    ]
