# Generated by Django 5.2.9 on 2025-12-20 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_tipo_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='tipo_materia',
        ),
    ]
