# Generated by Django 5.2.7 on 2025-11-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registration_code',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True, verbose_name='Código de Registro'),
        ),
    ]
