# Generated by Django 5.2.7 on 2025-12-05 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_registration_code'),
        ('teachers', '0003_teacher_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='teachers.teacher', verbose_name='Docente'),
        ),
    ]
