# Generated by Django 5.2.9 on 2025-12-16 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_gradelevel'),
        ('students', '0005_alter_student_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.AddField(
            model_name='student',
            name='grade_deprecated',
            field=models.CharField(blank=True, help_text='Este campo es obsoleto y será eliminado.', max_length=50, null=True, verbose_name='Año escolar (Antiguo)'),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classes.gradelevel', verbose_name='Grado'),
        ),
    ]
