# Generated by Django 5.2.9 on 2025-12-16 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_student_grade_student_grade_deprecated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade_deprecated',
        ),
    ]
