# Generated by Django 5.2.9 on 2025-12-18 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_usuario_alter_student_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['usuario__nombre'], 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
