version: '3.8'

# Overrides para desarrollo local
services:
  redis:
    command: redis-server --appendonly yes

  api:
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3 --threads 2 --access-logfile - --error-logfile -"
    environment:
      - ALLOWED_HOSTS=localhost,127.0.0.1,76.13.229.236,sga1.12t4ag.easypanel.host,api,sga1_api,sga1_django_web

  celery_worker:
    command: celery -A config worker -l info --concurrency=2

  celery_beat:
    command: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
