# Generated by Django 5.2.9 on 2025-12-20 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.PositiveIntegerField(verbose_name='Número de clase')),
                ('date', models.DateField(verbose_name='Fecha de clase')),
                ('topics_worked', models.TextField(blank=True, verbose_name='Temas trabajados')),
                ('techniques', models.TextField(blank=True, verbose_name='Técnicas desarrolladas')),
                ('pieces', models.CharField(blank=True, max_length=500, verbose_name='Piezas/Repertorio')),
                ('performance', models.CharField(choices=[('Excelente', 'Excelente'), ('Muy Bueno', 'Muy Bueno'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Necesita mejorar', 'Necesita mejorar')], default='Bueno', max_length=50, verbose_name='Desempeño')),
                ('strengths', models.TextField(blank=True, verbose_name='Fortalezas')),
                ('areas_to_improve', models.TextField(blank=True, verbose_name='Áreas a mejorar')),
                ('homework', models.TextField(blank=True, verbose_name='Tareas para casa')),
                ('practice_time', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(180)], verbose_name='Tiempo de práctica (minutos)')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-date', '-class_number'],
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente'), ('Justificado', 'Justificado')], max_length=20)),
                ('observacion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('status', models.CharField(choices=[('Presente', '✅ Presente'), ('Ausente', '❌ Ausente'), ('Tardanza', '⏰ Tardanza'), ('Justificado', '📝 Justificado')], default='Presente', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['-fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CalificacionParcial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcial', models.CharField(choices=[('1P', 'Primer Parcial'), ('2P', 'Segundo Parcial'), ('3P', 'Tercer Parcial'), ('4P', 'Cuarto Parcial')], max_length=2, verbose_name='Parcial')),
                ('quimestre', models.CharField(choices=[('Q1', 'Primer Quimestre'), ('Q2', 'Segundo Quimestre')], default='Q1', max_length=2, verbose_name='Quimestre')),
                ('calificacion', models.DecimalField(decimal_places=2, default=0, help_text='Nota sobre 10', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Calificación')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Última Actualización')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Calificación Parcial',
                'verbose_name_plural': 'Calificaciones Parciales',
                'ordering': ['-fecha_actualizacion', 'student__usuario__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la clase')),
                ('ciclo_lectivo', models.CharField(default='2025-2026', max_length=20, verbose_name='Ciclo lectivo')),
                ('paralelo', models.CharField(blank=True, default='', max_length=100, verbose_name='Paralelo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('schedule', models.CharField(blank=True, max_length=200, verbose_name='Horario')),
                ('room', models.CharField(blank=True, max_length=100, verbose_name='Aula/Salón')),
                ('max_students', models.PositiveIntegerField(default=30, verbose_name='Capacidad máxima')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('periodo', models.CharField(blank=True, max_length=100, verbose_name='Período Académico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'ordering': ['subject', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Deber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField()),
                ('puntos_totales', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='deberes/adjuntos/')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activo', 'Activo'), ('cerrado', 'Cerrado')], default='activo', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Deberes',
                'ordering': ['-fecha_entrega'],
            },
        ),
        migrations.CreateModel(
            name='DeberEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('archivo_entrega', models.FileField(blank=True, null=True, upload_to='deberes/entregas/')),
                ('comentario', models.TextField(blank=True)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('retroalimentacion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('revisado', 'Revisado'), ('tarde', 'Entregado Tarde')], default='pendiente', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Entregas de Deberes',
                'ordering': ['-fecha_entrega'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('RETIRADO', 'Retirado')], default='ACTIVO', max_length=20)),
                ('date_enrolled', models.DateTimeField(auto_now_add=True)),
                ('tipo_materia', models.CharField(choices=[('TEORICA', 'Teórica'), ('AGRUPACION', 'Agrupación'), ('INSTRUMENTO', 'Instrumento')], default='TEORICA', max_length=20)),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('Primer Parcial', 'Primer Parcial'), ('Segundo Parcial', 'Segundo Parcial'), ('Tercer Parcial', 'Tercer Parcial'), ('Examen Final', 'Examen Final'), ('Quimestre 1', 'Quimestre 1'), ('Quimestre 2', 'Quimestre 2')], max_length=50, verbose_name='Período')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Calificación')),
                ('comments', models.TextField(blank=True, verbose_name='Comentarios')),
                ('date', models.DateField(verbose_name='Fecha de calificación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto'), ('6', 'Sexto'), ('7', 'Séptimo'), ('8', 'Octavo'), ('9', 'Noveno'), ('10', 'Décimo'), ('11', 'Onceavo')], max_length=20, verbose_name='Nivel')),
                ('section', models.CharField(max_length=100, verbose_name='Paralelo/Sección')),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
                'ordering': ['level', 'section'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20, verbose_name='Día de la Semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PromedioCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcial', models.CharField(blank=True, max_length=2)),
                ('quimestre', models.CharField(blank=True, max_length=2)),
                ('tipo_promedio', models.CharField(choices=[('parcial', 'Parcial'), ('quimestre', 'Quimestre'), ('general', 'General')], max_length=20)),
                ('promedio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promedio (Cache)',
                'verbose_name_plural': 'Promedios (Cache)',
            },
        ),
        migrations.CreateModel(
            name='TipoAporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del aporte')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('peso', models.DecimalField(decimal_places=2, default=1.0, help_text='Peso relativo de este aporte en el cálculo del promedio', max_digits=5, verbose_name='Peso en el promedio')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Aporte',
                'verbose_name_plural': 'Tipos de Aportes',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
