# Generated by Django 5.2.7 on 2025-11-09 02:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_alter_student_grade'),
        ('teachers', '0002_teacher_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del aporte')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('peso', models.DecimalField(decimal_places=2, default=1.0, help_text='Peso relativo de este aporte en el cálculo del promedio', max_digits=5, verbose_name='Peso en el promedio')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Aporte',
                'verbose_name_plural': 'Tipos de Aportes',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la clase')),
                ('subject', models.CharField(max_length=120, verbose_name='Materia')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('schedule', models.CharField(blank=True, max_length=200, verbose_name='Horario')),
                ('room', models.CharField(blank=True, max_length=100, verbose_name='Aula/Salón')),
                ('max_students', models.PositiveIntegerField(default=30, verbose_name='Capacidad máxima')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_teoricas', to='teachers.teacher', verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Clase Teórica',
                'verbose_name_plural': 'Clases Teóricas',
                'ordering': ['subject', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estudiantes', models.ManyToManyField(blank=True, related_name='cursos_estudiante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cursos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(default='#ffffff', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='classes.curso')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_profesor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Materias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Deber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField()),
                ('puntos_totales', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='deberes/adjuntos/')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activo', 'Activo'), ('cerrado', 'Cerrado')], default='activo', max_length=20)),
                ('cursos', models.ManyToManyField(blank=True, related_name='deberes', to='classes.curso')),
                ('estudiantes_especificos', models.ManyToManyField(blank=True, related_name='deberes_asignados', to=settings.AUTH_USER_MODEL)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deberes_profesor', to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deberes', to='classes.materia')),
            ],
            options={
                'verbose_name_plural': 'Deberes',
                'ordering': ['-fecha_entrega'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('status', models.CharField(choices=[('Presente', '✅ Presente'), ('Ausente', '❌ Ausente'), ('Tardanza', '⏰ Tardanza'), ('Justificado', '📝 Justificado')], default='Presente', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120, verbose_name='Materia')),
                ('class_number', models.PositiveIntegerField(verbose_name='Número de clase')),
                ('date', models.DateField(verbose_name='Fecha de clase')),
                ('topics_worked', models.TextField(blank=True, verbose_name='Temas trabajados')),
                ('techniques', models.TextField(blank=True, verbose_name='Técnicas desarrolladas')),
                ('pieces', models.CharField(blank=True, max_length=500, verbose_name='Piezas/Repertorio')),
                ('performance', models.CharField(choices=[('Excelente', 'Excelente'), ('Muy Bueno', 'Muy Bueno'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Necesita mejorar', 'Necesita mejorar')], default='Bueno', max_length=50, verbose_name='Desempeño')),
                ('strengths', models.TextField(blank=True, verbose_name='Fortalezas')),
                ('areas_to_improve', models.TextField(blank=True, verbose_name='Áreas a mejorar')),
                ('homework', models.TextField(blank=True, verbose_name='Tareas para casa')),
                ('practice_time', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(180)], verbose_name='Tiempo de práctica (minutos)')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='students.student', verbose_name='Estudiante')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='classes.clase')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-date', '-class_number'],
                'unique_together': {('student', 'subject', 'class_number')},
            },
        ),
        migrations.CreateModel(
            name='DeberEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('archivo_entrega', models.FileField(blank=True, null=True, upload_to='deberes/entregas/')),
                ('comentario', models.TextField(blank=True)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('retroalimentacion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('revisado', 'Revisado'), ('tarde', 'Entregado Tarde')], default='pendiente', max_length=20)),
                ('deber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='classes.deber')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_entregas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Entregas de Deberes',
                'ordering': ['-fecha_entrega'],
                'unique_together': {('deber', 'estudiante')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classes.clase')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'unique_together': {('student', 'clase')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120, verbose_name='Materia')),
                ('period', models.CharField(choices=[('Primer Parcial', 'Primer Parcial'), ('Segundo Parcial', 'Segundo Parcial'), ('Tercer Parcial', 'Tercer Parcial'), ('Examen Final', 'Examen Final'), ('Quimestre 1', 'Quimestre 1'), ('Quimestre 2', 'Quimestre 2')], max_length=50, verbose_name='Período')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Calificación')),
                ('comments', models.TextField(blank=True, verbose_name='Comentarios')),
                ('date', models.DateField(verbose_name='Fecha de calificación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['-date'],
                'unique_together': {('student', 'subject', 'period')},
            },
        ),
        migrations.CreateModel(
            name='PromedioCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('parcial', models.CharField(blank=True, max_length=2)),
                ('quimestre', models.CharField(blank=True, max_length=2)),
                ('tipo_promedio', models.CharField(choices=[('parcial', 'Parcial'), ('quimestre', 'Quimestre'), ('general', 'General')], max_length=20)),
                ('promedio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cache_promedios', to='students.student')),
            ],
            options={
                'verbose_name': 'Promedio (Cache)',
                'verbose_name_plural': 'Promedios (Cache)',
                'indexes': [models.Index(fields=['student', 'tipo_promedio'], name='classes_pro_student_d02d7e_idx')],
                'unique_together': {('student', 'subject', 'parcial', 'quimestre', 'tipo_promedio')},
            },
        ),
        migrations.CreateModel(
            name='CalificacionParcial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120, verbose_name='Materia')),
                ('parcial', models.CharField(choices=[('1P', 'Primer Parcial'), ('2P', 'Segundo Parcial'), ('3P', 'Tercer Parcial'), ('4P', 'Cuarto Parcial')], max_length=2, verbose_name='Parcial')),
                ('quimestre', models.CharField(choices=[('Q1', 'Primer Quimestre'), ('Q2', 'Segundo Quimestre')], default='Q1', max_length=2, verbose_name='Quimestre')),
                ('calificacion', models.DecimalField(decimal_places=2, default=0, help_text='Nota sobre 10', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Calificación')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Última Actualización')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher', verbose_name='Registrado por')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_parciales', to='students.student', verbose_name='Estudiante')),
                ('tipo_aporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='classes.tipoaporte', verbose_name='Tipo de Aporte')),
            ],
            options={
                'verbose_name': 'Calificación Parcial',
                'verbose_name_plural': 'Calificaciones Parciales',
                'ordering': ['-fecha_actualizacion', 'student__name'],
                'indexes': [models.Index(fields=['student', 'subject', 'parcial'], name='classes_cal_student_89dfc8_idx'), models.Index(fields=['student', 'quimestre'], name='classes_cal_student_e4570e_idx'), models.Index(fields=['parcial', 'quimestre'], name='classes_cal_parcial_700fb2_idx')],
                'unique_together': {('student', 'subject', 'parcial', 'quimestre', 'tipo_aporte')},
            },
        ),
    ]
