# Generated by Django 4.2.19 on 2025-11-09 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deber',
            old_name='profesor',
            new_name='teacher',
        ),
        migrations.RemoveField(
            model_name='deber',
            name='materia',
        ),
        migrations.AddField(
            model_name='deber',
            name='clase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deberes', to='classes.clase'),
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
    ]
