# Generated by Django 5.2.6 on 2025-10-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='subject',
            field=models.CharField(choices=[('Agrupaciones_Ensamble de Guitarras', '🎸 Ensamble de Guitarras'), ('Agrupaciones_Banda Sinfónica Edison Chiluisa', '🎵 Banda Sinfónica Edison Chiluisa'), ('Agrupaciones_Coro Vespertino', '🎵 Coro'), ('Agrupaciones_Orquesta', '🎵 Orquesta'), ('Conjunto Instrumental_Orquesta', '🎵 Orquesta Infantil'), ('Conjunto Instrumental_Ensamble_vientos', '🎵 Ensamble Vientos'), ('Conjunto Instrumental_Orquesta_pedagogica', '🎵 Orquesta pedagogica'), ('Materias_teoricas_Audioperceptiva', '🎶 Audioperceptiva'), ('Materias_teoricas_Leguaje_Musical', '🎶 Leguaje Musical'), ('Materias_teoricas_Historia_Musica', '🎶 Historia de la Música'), ('Materias_teoricas_Formacion_Laboral', '🎶 Formación y Orientación Laboral'), ('Materias_teoricas_Capacitacion_Musica', '🎶 Capacitación en Música'), ('Materias_teoricas_Armonia', '🎶 Armonia'), ('Materias_teoricas_Informatica', '🎶 Informatica'), ('Materias_teoricas_Formas', '🎶 Formas Musicales'), ('Materias_teoricas_Arreglos', '🎶 Creación y Arreglos Musicales'), ('Materias_teoricas_Produccion', '🎶 Produccion Artistico Musical'), ('Guitarra Clásica', '🎸 Guitarra Clásica'), ('Cuerdas_Violin', '🎻 Cuerdas Violín'), ('Cuerdas_Viola', '🎻 Cuerdas Viola'), ('Cuerdas_Violonchello', '🎻 Cuerdas Violonchello'), ('Cuerdas_Contrabajo', '🎻 Cuerdas Contrabajo'), ('Piano', '🎹 Piano'), ('Piano_Acompañamiento', '🎹 Piano Acompañamiento'), ('Piano Complementario', '🎹 Piano Complementario'), ('Vientos_Clarinete', ' 🎷 Vientos Clarinete'), ('Vientos_Trompeta', ' 🎺 Vientos Trompeta'), ('Vientos_Saxofon', ' 🎷 Vientos Saxofon'), ('Vientos_Flauta', ' 🎷 Vientos Flauta'), ('Vientos_Trombon', ' 🎷 Vientos Trombon'), ('Percusion', ' 🥁 Percusion')], max_length=100, verbose_name='Materia'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.CharField(choices=[('Agrupaciones_Ensamble de Guitarras', '🎸 Ensamble de Guitarras'), ('Agrupaciones_Banda Sinfónica Edison Chiluisa', '🎵 Banda Sinfónica Edison Chiluisa'), ('Agrupaciones_Coro Vespertino', '🎵 Coro'), ('Agrupaciones_Orquesta', '🎵 Orquesta'), ('Conjunto Instrumental_Orquesta', '🎵 Orquesta Infantil'), ('Conjunto Instrumental_Ensamble_vientos', '🎵 Ensamble Vientos'), ('Conjunto Instrumental_Orquesta_pedagogica', '🎵 Orquesta pedagogica'), ('Materias_teoricas_Audioperceptiva', '🎶 Audioperceptiva'), ('Materias_teoricas_Leguaje_Musical', '🎶 Leguaje Musical'), ('Materias_teoricas_Historia_Musica', '🎶 Historia de la Música'), ('Materias_teoricas_Formacion_Laboral', '🎶 Formación y Orientación Laboral'), ('Materias_teoricas_Capacitacion_Musica', '🎶 Capacitación en Música'), ('Materias_teoricas_Armonia', '🎶 Armonia'), ('Materias_teoricas_Informatica', '🎶 Informatica'), ('Materias_teoricas_Formas', '🎶 Formas Musicales'), ('Materias_teoricas_Arreglos', '🎶 Creación y Arreglos Musicales'), ('Materias_teoricas_Produccion', '🎶 Produccion Artistico Musical'), ('Guitarra Clásica', '🎸 Guitarra Clásica'), ('Cuerdas_Violin', '🎻 Cuerdas Violín'), ('Cuerdas_Viola', '🎻 Cuerdas Viola'), ('Cuerdas_Violonchello', '🎻 Cuerdas Violonchello'), ('Cuerdas_Contrabajo', '🎻 Cuerdas Contrabajo'), ('Piano', '🎹 Piano'), ('Piano_Acompañamiento', '🎹 Piano Acompañamiento'), ('Piano Complementario', '🎹 Piano Complementario'), ('Vientos_Clarinete', ' 🎷 Vientos Clarinete'), ('Vientos_Trompeta', ' 🎺 Vientos Trompeta'), ('Vientos_Saxofon', ' 🎷 Vientos Saxofon'), ('Vientos_Flauta', ' 🎷 Vientos Flauta'), ('Vientos_Trombon', ' 🎷 Vientos Trombon'), ('Percusion', ' 🥁 Percusion')], max_length=100, verbose_name='Materia'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('2do Básica', '2do Básica'), ('3ro Básica', '3ro Básica'), ('4to Básica', '4to Básica'), ('5to Básica', '5to Básica'), ('6to Básica', '6to Básica'), ('7mo Básica', '7mo Básica'), ('8vo Básica', '8vo Básica'), ('9no Básica', '9no Básica'), ('10mo Básica', '10mo Básica'), ('11mo Básica', '11mo Básica')], max_length=50, verbose_name='Año escolar'),
        ),
    ]
