# Generated by Django 5.2.6 on 2025-10-02 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_activity_subject_alter_grade_subject_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del estudiante'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='subject',
            field=models.CharField(choices=[('Guitarra Clásica', '🎸 Guitarra Clásica'), ('Conjunto Instrumental', '🎺 Conjunto Instrumental'), ('Creación y Arreglos Musicales', '🎵 Creación y Arreglos Musicales')], max_length=100, verbose_name='Materia'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.CharField(choices=[('Guitarra Clásica', '🎸 Guitarra Clásica'), ('Conjunto Instrumental', '🎺 Conjunto Instrumental'), ('Creación y Arreglos Musicales', '🎵 Creación y Arreglos Musicales')], max_length=100, verbose_name='Materia'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('2do Básica', '2do Básica'), ('3ro Básica', '3ro Básica'), ('4to Básica', '4to Básica'), ('5to Básica', '5to Básica'), ('6to Básica', '6to Básica'), ('7mo Básica', '7mo Básica'), ('8vo Básica', '8vo Básica'), ('9no Básica', '9no Básica'), ('10mo Básica', '10mo Básica'), ('1ro Bachillerato', '1ro Bachillerato'), ('2do Bachillerato', '2do Bachillerato'), ('3ro Bachillerato', '3ro Bachillerato')], max_length=50, verbose_name='Año escolar'),
        ),
    ]
