# Generated by Django 5.2.9 on 2025-12-18 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_gradelevel'),
        ('teachers', '0004_teacher_grades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='teacher',
        ),
        migrations.AddField(
            model_name='clase',
            name='grade_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases', to='classes.gradelevel', verbose_name='Nivel/Paralelo'),
        ),
        migrations.AddField(
            model_name='clase',
            name='periodo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Período Académico'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments_as_teacher', to='teachers.teacher', verbose_name='Docente Asignado'),
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20, verbose_name='Día de la Semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='classes.clase', verbose_name='Clase')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('clase', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
