# Generated by Django 5.2.9 on 2025-12-20 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_gradelevel_docente_tutor'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradelevel',
            name='docente_tutor',
        ),
        migrations.AlterField(
            model_name='clase',
            name='docente_base',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_como_docente_base', to='users.usuario', verbose_name='Docente base'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='docente',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments_as_teacher', to='users.usuario', verbose_name='Docente asignado'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='tipo_materia',
            field=models.CharField(choices=[('TEORICA', 'Teórica (Grupal)'), ('AGRUPACION', 'Agrupación (Ensamble)'), ('INSTRUMENTO', 'Instrumento (Individual)')], default='TEORICA', max_length=20),
        ),
    ]
