# Generated by Django 5.2.6 on 2025-10-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_student_unique_together_student_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('2do Básica', '2do Básica'), ('3ro Básica', '3ro Básica'), ('4to Básica', '4to Básica'), ('5to Básica', '5to Básica'), ('6to Básica', '6to Básica'), ('7mo Básica', '7mo Básica'), ('8vo Básica', '8vo Básica'), ('1ro Bachillerato', '1ro Bachillerato'), ('2do Bachillerato', '2do Bachillerato'), ('3ro Bachillerato', '3ro Bachillerato')], max_length=50, verbose_name='Año escolar'),
        ),
    ]
