# Generated by Django 5.2.9 on 2025-12-18 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_remove_clase_teacher_clase_grade_level_clase_periodo_and_more'),
        ('subjects', '0002_subject_tipo_materia'),
        ('users', '0002_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente'), ('Justificado', 'Justificado')], max_length=20)),
                ('observacion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['-fecha', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='clase',
            options={'ordering': ['subject', 'name'], 'verbose_name': 'Clase', 'verbose_name_plural': 'Clases'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Inscripción', 'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.AddField(
            model_name='clase',
            name='ciclo_lectivo',
            field=models.CharField(default='2025-2026', max_length=20, verbose_name='Ciclo lectivo'),
        ),
        migrations.AddField(
            model_name='clase',
            name='docente_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_como_docente_base', to='users.usuario', verbose_name='Docente base'),
        ),
        migrations.AddField(
            model_name='clase',
            name='paralelo',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Paralelo'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments_as_teacher', to='users.usuario', verbose_name='Docente asignado'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('RETIRADO', 'Retirado')], default='ACTIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments_as_student', to='users.usuario', verbose_name='Estudiante'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('estudiante', 'clase')},
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classes.clase', verbose_name='Clase'),
        ),
        migrations.AddConstraint(
            model_name='clase',
            constraint=models.UniqueConstraint(condition=models.Q(('docente_base__isnull', True)), fields=('subject', 'ciclo_lectivo', 'paralelo'), name='uniq_clase_subject_ciclo_paralelo_when_no_docente_base'),
        ),
        migrations.AddConstraint(
            model_name='clase',
            constraint=models.UniqueConstraint(condition=models.Q(('docente_base__isnull', False)), fields=('subject', 'ciclo_lectivo', 'docente_base'), name='uniq_clase_subject_ciclo_docente_base_when_docente_base'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='classes.enrollment'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='classes.enrollment'),
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='active',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='teacher',
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('inscripcion', 'fecha')},
        ),
    ]
