# Generated by Django 5.2.9 on 2025-12-18 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_asistencia_calificacion_alter_clase_options_and_more'),
        ('users', '0002_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deber',
            name='cursos',
        ),
        migrations.AlterModelOptions(
            name='calificacionparcial',
            options={'ordering': ['-fecha_actualizacion', 'student__usuario__nombre'], 'verbose_name': 'Calificación Parcial', 'verbose_name_plural': 'Calificaciones Parciales'},
        ),
        migrations.AlterField(
            model_name='deber',
            name='estudiantes_especificos',
            field=models.ManyToManyField(blank=True, related_name='deberes_asignados', to='users.usuario'),
        ),
        migrations.AlterField(
            model_name='deber',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deberes_profesor', to='users.usuario'),
        ),
        migrations.AlterField(
            model_name='deberentrega',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_entregas', to='users.usuario'),
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
