# Generated by Django 5.2.6 on 2025-10-15 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_enrollment'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student', verbose_name='Estudiante'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student', verbose_name='Estudiante'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='students.student', verbose_name='Estudiante'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student'),
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la clase')),
                ('subject', models.CharField(choices=[('Guitarra Clásica', '🎸 Guitarra Clásica'), ('Conjunto Instrumental', '🎺 Conjunto Instrumental'), ('Creación y Arreglos Musicales', '🎵 Creación y Arreglos Musicales')], max_length=100, verbose_name='Materia')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('schedule', models.CharField(blank=True, max_length=200, verbose_name='Horario')),
                ('room', models.CharField(blank=True, max_length=100, verbose_name='Aula/Salón')),
                ('max_students', models.PositiveIntegerField(default=30, verbose_name='Capacidad máxima')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_teoricas', to='teachers.teacher', verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Clase Teórica',
                'verbose_name_plural': 'Clases Teóricas',
                'ordering': ['subject', 'name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='clase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classes.clase'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'clase')},
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='activity',
        ),
    ]
