# Generated by Django 5.2.9 on 2025-12-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_gradelevel_docente_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='ciclo_lectivo',
            field=models.CharField(default='2025-2026', max_length=100, verbose_name='Ciclo lectivo'),
        ),
    ]
