# Generated by Django 5.2.6 on 2025-10-15 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_alter_grade_student_alter_attendance_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='clase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='classes.clase'),
            preserve_default=False,
        ),
    ]
