# Generated by Django 5.2.6 on 2025-10-29 22:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_activity_clase'),
        ('students', '0002_student_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaCualitativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('nota_minima', models.DecimalField(decimal_places=2, max_digits=4)),
                ('nota_maxima', models.DecimalField(decimal_places=2, max_digits=4)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
            ],
            options={
                'verbose_name': 'Escala Cualitativa',
                'verbose_name_plural': 'Escalas Cualitativas',
                'ordering': ['-nota_minima'],
            },
        ),
        migrations.CreateModel(
            name='TipoAporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del aporte')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('peso', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Peso en el promedio')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Aporte',
                'verbose_name_plural': 'Tipos de Aportes',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='CalificacionParcial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Guitarra Clásica', '🎸 Guitarra Clásica'), ('Conjunto Instrumental', '🎺 Conjunto Instrumental'), ('Creación y Arreglos Musicales', '🎵 Creación y Arreglos Musicales')], max_length=100)),
                ('parcial', models.CharField(choices=[('1P', 'Primer Parcial'), ('2P', 'Segundo Parcial'), ('3P', 'Tercer Parcial')], max_length=2)),
                ('calificacion', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_parciales', to='students.student')),
                ('tipo_aporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.tipoaporte')),
            ],
            options={
                'verbose_name': 'Calificación Parcial',
                'verbose_name_plural': 'Calificaciones Parciales',
                'ordering': ['-fecha_registro'],
                'unique_together': {('student', 'subject', 'parcial', 'tipo_aporte')},
            },
        ),
    ]
