# Generated by Django 5.2.6 on 2025-10-30 21:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_escalacualitativa_tipoaporte_calificacionparcial'),
        ('students', '0002_student_photo'),
        ('teachers', '0002_teacher_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromedioCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('parcial', models.CharField(blank=True, max_length=2)),
                ('quimestre', models.CharField(blank=True, max_length=2)),
                ('tipo_promedio', models.CharField(choices=[('parcial', 'Parcial'), ('quimestre', 'Quimestre'), ('general', 'General')], max_length=20)),
                ('promedio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promedio (Cache)',
                'verbose_name_plural': 'Promedios (Cache)',
            },
        ),
        migrations.DeleteModel(
            name='EscalaCualitativa',
        ),
        migrations.AlterModelOptions(
            name='calificacionparcial',
            options={'ordering': ['-fecha_actualizacion', 'student__name'], 'verbose_name': 'Calificación Parcial', 'verbose_name_plural': 'Calificaciones Parciales'},
        ),
        migrations.AlterModelOptions(
            name='tipoaporte',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Tipo de Aporte', 'verbose_name_plural': 'Tipos de Aportes'},
        ),
        migrations.AlterUniqueTogether(
            name='calificacionparcial',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='calificacionparcial',
            name='fecha_actualizacion',
            field=models.DateField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='calificacionparcial',
            name='quimestre',
            field=models.CharField(choices=[('Q1', 'Primer Quimestre'), ('Q2', 'Segundo Quimestre')], default='Q1', max_length=2, verbose_name='Quimestre'),
        ),
        migrations.AddField(
            model_name='calificacionparcial',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher', verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='tipoaporte',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipoaporte',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='calificacionparcial',
            name='calificacion',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Nota sobre 10', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='calificacionparcial',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='calificacionparcial',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='calificacionparcial',
            name='parcial',
            field=models.CharField(choices=[('1P', 'Primer Parcial'), ('2P', 'Segundo Parcial'), ('3P', 'Tercer Parcial'), ('4P', 'Cuarto Parcial')], max_length=2, verbose_name='Parcial'),
        ),
        migrations.AlterField(
            model_name='calificacionparcial',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_parciales', to='students.student', verbose_name='Estudiante'),
        ),
        migrations.AlterField(
            model_name='calificacionparcial',
            name='subject',
            field=models.CharField(help_text='Usar los códigos de Activity.SUBJECT_CHOICES', max_length=100, verbose_name='Materia'),
        ),
        migrations.AlterField(
            model_name='calificacionparcial',
            name='tipo_aporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='classes.tipoaporte', verbose_name='Tipo de Aporte'),
        ),
        migrations.AlterField(
            model_name='tipoaporte',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='tipoaporte',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Peso relativo de este aporte en el cálculo del promedio', max_digits=5, verbose_name='Peso en el promedio'),
        ),
        migrations.AlterUniqueTogether(
            name='calificacionparcial',
            unique_together={('student', 'subject', 'parcial', 'quimestre', 'tipo_aporte')},
        ),
        migrations.AddIndex(
            model_name='calificacionparcial',
            index=models.Index(fields=['student', 'subject', 'parcial'], name='classes_cal_student_89dfc8_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacionparcial',
            index=models.Index(fields=['student', 'quimestre'], name='classes_cal_student_e4570e_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacionparcial',
            index=models.Index(fields=['parcial', 'quimestre'], name='classes_cal_parcial_700fb2_idx'),
        ),
        migrations.AddField(
            model_name='promediocache',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cache_promedios', to='students.student'),
        ),
        migrations.AddIndex(
            model_name='promediocache',
            index=models.Index(fields=['student', 'tipo_promedio'], name='classes_pro_student_d02d7e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='promediocache',
            unique_together={('student', 'subject', 'parcial', 'quimestre', 'tipo_promedio')},
        ),
    ]
