# Generated by Django 5.2.7 on 2025-10-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_promediocache_delete_escalacualitativa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='subject',
            field=models.CharField(max_length=120, verbose_name='Materia'),
        ),
        migrations.AlterField(
            model_name='calificacionparcial',
            name='subject',
            field=models.CharField(max_length=120, verbose_name='Materia'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='subject',
            field=models.CharField(max_length=120, verbose_name='Materia'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.CharField(max_length=120, verbose_name='Materia'),
        ),
    ]
