# Generated by Django 5.2.15 on 2026-06-30 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_usuario_rol_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo', models.CharField(choices=[('FERIADO', 'Feriado'), ('EXAMEN', 'Examen / Evaluación'), ('EVENTO', 'Evento'), ('QUIMESTRE', 'Inicio/Fin Quimestre'), ('REUNION', 'Reunión')], default='EVENTO', max_length=15)),
                ('color', models.CharField(default='#4338ca', max_length=7)),
                ('visible_para', models.CharField(choices=[('ALL', 'Todos'), ('DOCENTES', 'Solo Docentes'), ('ESTUDIANTES', 'Solo Estudiantes')], default='ALL', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_creados', to='users.usuario')),
            ],
            options={
                'verbose_name': 'Evento del Calendario',
                'verbose_name_plural': 'Eventos del Calendario',
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
