# Generated by Django 5.2.9 on 2025-12-20 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, default='', max_length=120, verbose_name='Especialidad')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/teachers/', verbose_name='Foto de perfil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to='users.usuario', verbose_name='Usuario unificado')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'ordering': ['usuario__nombre'],
            },
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Materia Asignada a Docente',
                'verbose_name_plural': 'Materias Asignadas a Docentes',
                'unique_together': {('teacher', 'subject')},
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', through='teachers.TeacherSubject', to='subjects.subject', verbose_name='Materias asignadas'),
        ),
    ]
