# Generated by Django 5.2.9 on 2025-12-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_gradelevel'),
        ('teachers', '0003_teacher_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='grades',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='classes.gradelevel', verbose_name='Grados'),
        ),
    ]
