# Generated by Django 5.2.9 on 2025-12-18 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_teacher_grades'),
        ('users', '0002_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to='users.usuario', verbose_name='Usuario unificado'),
        ),
    ]
