# Generated by Django 5.2.9 on 2025-12-19 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_alter_teacher_options_remove_teacher_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
    ]
