# Generated by Django 5.2.9 on 2025-12-22 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0005_gradelevel_docente_tutor'),
        ('subjects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=20, verbose_name='Día')),
                ('hora', models.CharField(max_length=50, verbose_name='Rango Horario')),
                ('aula', models.CharField(blank=True, max_length=100, verbose_name='Aula')),
                ('clase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.subject', verbose_name='Clase / Asignatura')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.gradelevel', verbose_name='Curso')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.usuario', verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['curso__level', 'curso__section', 'dia', 'hora'],
                'unique_together': {('curso', 'dia', 'hora', 'clase', 'docente', 'aula')},
            },
        ),
    ]
