# Generated by Django 5.2.9 on 2025-12-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nombre de la materia')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo_materia', models.CharField(choices=[('TEORIA', 'Teoría'), ('AGRUPACION', 'Agrupación'), ('INSTRUMENTO', 'Instrumento'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Tipo de Materia')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['name'],
            },
        ),
    ]
