# Generated by Django 5.2.15 on 2026-06-30 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0004_student_representante_usuario'),
        ('users', '0002_alter_usuario_rol_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('CUERDA', 'Cuerda'), ('VIENTO', 'Viento'), ('PERCUSION', 'Percusión'), ('TECLADO', 'Teclado'), ('OTRO', 'Otro')], default='OTRO', max_length=15)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('PRESTADO', 'Prestado'), ('MANTENIMIENTO', 'En Mantenimiento'), ('BAJA', 'Baja')], default='DISPONIBLE', max_length=15)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Instrumento',
                'verbose_name_plural': 'Instrumentos',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PrestamoInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(auto_now_add=True)),
                ('fecha_devolucion_esperada', models.DateField()),
                ('fecha_devolucion_real', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('DEVUELTO', 'Devuelto'), ('VENCIDO', 'Vencido')], default='ACTIVO', max_length=10)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_instrumentos', to='students.student')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='inventario.instrumento')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_registrados', to='users.usuario')),
            ],
            options={
                'verbose_name': 'Préstamo de Instrumento',
                'verbose_name_plural': 'Préstamos de Instrumentos',
                'ordering': ['-fecha_prestamo'],
            },
        ),
    ]
