# Generated by Django 5.2.15 on 2026-06-24 20:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0007_add_ciclo_grade_level_and_malla_curricular'),
        ('students', '0003_remove_student_tipo_materia'),
        ('subjects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_instancia', models.CharField(max_length=100, unique=True, verbose_name='Nombre de instancia')),
                ('activa', models.BooleanField(default=False, verbose_name='Activa')),
                ('ciclo_lectivo', models.CharField(default='2025-2026', max_length=20, verbose_name='Ciclo Lectivo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración WhatsApp',
                'verbose_name_plural': 'Configuraciones WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='SesionClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('tema', models.CharField(blank=True, max_length=500, verbose_name='Tema')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('sheet_id', models.CharField(blank=True, max_length=200, verbose_name='ID de Hoja')),
                ('tab', models.CharField(blank=True, max_length=100, verbose_name='Pestaña')),
                ('col_index', models.IntegerField(blank=True, null=True, verbose_name='Índice columna')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_informe', to='classes.clase', verbose_name='Clase')),
            ],
            options={
                'verbose_name': 'Sesión de Clase',
                'verbose_name_plural': 'Sesiones de Clase',
                'ordering': ['fecha', 'col_index'],
                'unique_together': {('sheet_id', 'tab', 'col_index')},
            },
        ),
        migrations.CreateModel(
            name='SubmisionFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_nombre', models.CharField(max_length=200, verbose_name='Curso')),
                ('contenidos', models.TextField(blank=True, verbose_name='Contenidos trabajados')),
                ('acciones', models.TextField(blank=True, verbose_name='Acciones correctivas')),
                ('dificultades_json', models.JSONField(default=list, verbose_name='Estudiantes con dificultades')),
                ('form_url', models.URLField(blank=True, verbose_name='URL del Formulario')),
                ('form_fields_json', models.JSONField(default=list, verbose_name='Campos del formulario')),
                ('exito', models.BooleanField(default=False, verbose_name='Éxito')),
                ('error', models.TextField(blank=True, verbose_name='Error')),
                ('veces_enviado', models.PositiveIntegerField(default=1, verbose_name='Veces enviado')),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
                ('ultimo_envio', models.DateTimeField(auto_now=True)),
                ('docente', models.ForeignKey(blank=True, limit_choices_to={'rol': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submisiones_form', to='users.usuario', verbose_name='Docente')),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.subject', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Submisión de Formulario',
                'verbose_name_plural': 'Submisiones de Formularios',
                'ordering': ['-enviado_en'],
            },
        ),
        migrations.CreateModel(
            name='RegistroEnvioWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('1P', 'Primer Parcial'), ('2P', 'Segundo Parcial'), ('3P', 'Tercer Parcial'), ('4P', 'Cuarto Parcial'), ('1Q', 'Primer Quimestre'), ('2Q', 'Segundo Quimestre'), ('Anual', 'Anual'), ('A1', 'Asistencia Parcial 1'), ('A2', 'Asistencia Parcial 2'), ('A3', 'Asistencia Parcial 3'), ('A4', 'Asistencia Parcial 4')], max_length=10, verbose_name='Período')),
                ('ciclo_lectivo', models.CharField(default='2025-2026', max_length=20, verbose_name='Ciclo Lectivo')),
                ('mensaje', models.TextField(verbose_name='Mensaje enviado')),
                ('telefono_usado', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('estado_wa', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('fallido', 'Fallido')], default='pendiente', max_length=20, verbose_name='Estado WhatsApp')),
                ('estado_form', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('fallido', 'Fallido')], default='pendiente', max_length=20, verbose_name='Estado Formulario')),
                ('error_wa', models.TextField(blank=True, verbose_name='Error WhatsApp')),
                ('error_form', models.TextField(blank=True, verbose_name='Error Formulario')),
                ('enviado_en', models.DateTimeField(auto_now_add=True, verbose_name='Enviado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_whatsapp', to='students.student', verbose_name='Estudiante')),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_whatsapp', to='subjects.subject', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Registro de Envío WhatsApp',
                'verbose_name_plural': 'Registros de Envíos WhatsApp',
                'ordering': ['-enviado_en'],
                'indexes': [models.Index(fields=['estudiante', 'periodo'], name='informes_re_estudia_c330ed_idx'), models.Index(fields=['estado_wa'], name='informes_re_estado__ffe520_idx'), models.Index(fields=['-enviado_en'], name='informes_re_enviado_c267aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecomendacionEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomendacion', models.TextField(verbose_name='Recomendación')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones_clase', to='users.usuario', verbose_name='Estudiante')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='informes.sesionclase', verbose_name='Sesión')),
            ],
            options={
                'verbose_name': 'Recomendación de Estudiante',
                'verbose_name_plural': 'Recomendaciones de Estudiantes',
                'ordering': ['estudiante__nombre'],
                'unique_together': {('sesion', 'estudiante')},
            },
        ),
    ]
