# Generated by Django 5.2.7 on 2025-12-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='tipo_materia',
            field=models.CharField(choices=[('TEORIA', 'Teoría'), ('AGRUPACION', 'Agrupación'), ('INSTRUMENTO', 'Instrumento'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Tipo de Materia'),
        ),
    ]
