# Generated by Django 5.2.15 on 2026-06-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionInstitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200, verbose_name='Nombre de la institución')),
                ('siglas', models.CharField(blank=True, max_length=20, verbose_name='Siglas')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('direccion', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email institucional')),
                ('website', models.URLField(blank=True, verbose_name='Sitio web')),
                ('anio_lectivo', models.CharField(default='2025-2026', max_length=20, verbose_name='Año lectivo actual')),
                ('mision', models.TextField(blank=True, verbose_name='Misión')),
                ('vision', models.TextField(blank=True, verbose_name='Visión')),
            ],
            options={
                'verbose_name': 'Configuración de la Institución',
            },
        ),
    ]
