# Generated by Django 5.2.15 on 2026-06-25 16:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_seguimiento', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de revisión'), ('APROBADO', 'Aprobado — cuenta creada'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('cedula', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('especialidad', models.CharField(blank=True, max_length=120)),
                ('titulo_academico', models.CharField(blank=True, max_length=200)),
                ('experiencia_anios', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Años de experiencia')),
                ('mensaje', models.TextField(blank=True, verbose_name='Carta de presentación / mensaje adicional')),
                ('notas_admin', models.TextField(blank=True, verbose_name='Notas del administrador')),
                ('username_generado', models.CharField(blank=True, editable=False, max_length=60)),
                ('password_temporal', models.CharField(blank=True, editable=False, help_text='Contraseña visible sólo justo después de aprobar.', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Registro — Docente',
                'verbose_name_plural': 'Solicitudes de Registro — Docentes',
                'ordering': ['-created_at'],
            },
        ),
    ]
