# Generated by Django 5.2.14 on 2026-05-29 15:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_seguimiento', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('NUEVA', 'Inscripción nueva'), ('RENOVACION', 'Renovación de matrícula')], default='NUEVA', max_length=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de revisión'), ('EN_REVISION', 'En revisión'), ('NOVEDAD', 'Novedad — documentos a corregir'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=12)),
                ('anio_solicitado', models.PositiveSmallIntegerField()),
                ('instrumento_elegido', models.CharField(blank=True, default='', max_length=60)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('cedula', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('nombre_representante', models.CharField(blank=True, default='', max_length=150)),
                ('email_representante', models.EmailField(max_length=254)),
                ('phone_representante', models.CharField(max_length=20)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('ciudad', models.CharField(blank=True, default='', max_length=80)),
                ('ciclo_lectivo', models.CharField(max_length=12)),
                ('revision_ia_completada', models.BooleanField(default=False)),
                ('resumen_ia', models.TextField(blank=True, default='')),
                ('tiene_novedades_ia', models.BooleanField(default=False)),
                ('notas_secretaria', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas_revisadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_matricula', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Matrícula',
                'verbose_name_plural': 'Solicitudes de Matrícula',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CEDULA', 'Copia de Cédula / Acta de Nacimiento'), ('CERT_EDUCACION', 'Certificado de Educación Regular'), ('CERT_CONSERVATORIO', 'Certificado del Conservatorio'), ('FOTO_CARNET', 'Foto Carnet')], max_length=25)),
                ('archivo', models.FileField(upload_to='matriculas/documentos/%Y/%m/')),
                ('nombre_original', models.CharField(blank=True, max_length=255)),
                ('estado_ia', models.CharField(choices=[('PENDIENTE', 'Pendiente de análisis'), ('PROCESANDO', 'Procesando...'), ('VALIDO', 'Válido'), ('NOVEDAD', 'Con novedad'), ('ERROR', 'Error al procesar')], default='PENDIENTE', max_length=12)),
                ('observacion_ia', models.TextField(blank=True, default='')),
                ('confianza_ia', models.FloatField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='matriculas.solicitudmatricula')),
            ],
            options={
                'verbose_name': 'Documento de Matrícula',
                'verbose_name_plural': 'Documentos de Matrícula',
            },
        ),
    ]
