# Generated by Django 5.2.15 on 2026-06-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('area', models.CharField(blank=True, default='', max_length=120, verbose_name='Área')),
                ('telefono', models.CharField(blank=True, default='', max_length=30, verbose_name='Teléfono')),
                ('correo', models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo electrónico')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Director de Área',
                'verbose_name_plural': 'Directores de Área',
                'ordering': ['nombre'],
            },
        ),
    ]
