# Generated by Django 5.2.15 on 2026-06-30 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_directorarea'),
        ('users', '0002_alter_usuario_rol_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorarea',
            name='docente',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_areas', to='users.usuario', verbose_name='Docente (buscar por nombre)'),
        ),
        migrations.AlterField(
            model_name='directorarea',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nombre'),
        ),
    ]
