# Generated by Django 5.2.15 on 2026-06-30 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_directorarea_add_docente_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='Función')),
                ('descripcion', models.CharField(blank=True, default='', max_length=255, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Función Institucional',
                'verbose_name_plural': 'Funciones Institucionales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DocenteFuncion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, default='', max_length=120, verbose_name='Detalle (ej: área, curso)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funciones', to='teachers.teacher', verbose_name='Docente')),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='teachers.funcion', verbose_name='Función')),
            ],
            options={
                'verbose_name': 'Función Asignada',
                'verbose_name_plural': 'Funciones Asignadas',
                'ordering': ['teacher__usuario__nombre', 'funcion__nombre'],
                'unique_together': {('teacher', 'funcion', 'detalle')},
            },
        ),
    ]
