# Generated by Django 5.2.9 on 2025-12-20 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='students.student', verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='activity',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='subjects.subject', verbose_name='Materia'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student', verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='calificacionparcial',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher', verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='calificacionparcial',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_parciales', to='students.student', verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='calificacionparcial',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_parciales', to='subjects.subject', verbose_name='Materia'),
        ),
        migrations.AddField(
            model_name='clase',
            name='docente_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_como_docente_base', to='users.usuario', verbose_name='Docente base'),
        ),
        migrations.AddField(
            model_name='clase',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='subjects.subject', verbose_name='Materia'),
        ),
        migrations.AddField(
            model_name='activity',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='classes.clase'),
        ),
        migrations.AddField(
            model_name='deber',
            name='clase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deberes', to='classes.clase'),
        ),
        migrations.AddField(
            model_name='deber',
            name='estudiantes_especificos',
            field=models.ManyToManyField(blank=True, related_name='deberes_asignados', to='users.usuario'),
        ),
        migrations.AddField(
            model_name='deber',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deberes_profesor', to='users.usuario'),
        ),
        migrations.AddField(
            model_name='deberentrega',
            name='deber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='classes.deber'),
        ),
        migrations.AddField(
            model_name='deberentrega',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_entregas', to='users.usuario'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classes.clase', verbose_name='Clase'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments_as_teacher', to='users.usuario', verbose_name='Docente asignado'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments_as_student', to='users.usuario', verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='classes.enrollment'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='classes.enrollment'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student', verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='subjects.subject', verbose_name='Materia'),
        ),
        migrations.AlterUniqueTogether(
            name='gradelevel',
            unique_together={('level', 'section')},
        ),
        migrations.AddField(
            model_name='clase',
            name='grade_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases', to='classes.gradelevel', verbose_name='Nivel/Paralelo'),
        ),
        migrations.AddField(
            model_name='horario',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='classes.clase', verbose_name='Clase'),
        ),
        migrations.AddField(
            model_name='promediocache',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cache_promedios', to='students.student'),
        ),
        migrations.AddField(
            model_name='promediocache',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cache_promedios', to='subjects.subject', verbose_name='Materia'),
        ),
        migrations.AddField(
            model_name='calificacionparcial',
            name='tipo_aporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='classes.tipoaporte', verbose_name='Tipo de Aporte'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('student', 'subject', 'class_number')},
        ),
        migrations.AlterUniqueTogether(
            name='deberentrega',
            unique_together={('deber', 'estudiante')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('estudiante', 'clase')},
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('inscripcion', 'fecha')},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'subject', 'period')},
        ),
        migrations.AddConstraint(
            model_name='clase',
            constraint=models.UniqueConstraint(condition=models.Q(('docente_base__isnull', True)), fields=('subject', 'ciclo_lectivo', 'paralelo'), name='uniq_clase_subject_ciclo_paralelo_when_no_docente_base'),
        ),
        migrations.AddConstraint(
            model_name='clase',
            constraint=models.UniqueConstraint(condition=models.Q(('docente_base__isnull', False)), fields=('subject', 'ciclo_lectivo', 'docente_base'), name='uniq_clase_subject_ciclo_docente_base_when_docente_base'),
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('clase', 'dia_semana', 'hora_inicio')},
        ),
        migrations.AddIndex(
            model_name='promediocache',
            index=models.Index(fields=['student', 'tipo_promedio'], name='classes_pro_student_d02d7e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='promediocache',
            unique_together={('student', 'subject', 'parcial', 'quimestre', 'tipo_promedio')},
        ),
        migrations.AddIndex(
            model_name='calificacionparcial',
            index=models.Index(fields=['student', 'subject', 'parcial'], name='classes_cal_student_5f7d7b_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacionparcial',
            index=models.Index(fields=['student', 'quimestre'], name='classes_cal_student_e4570e_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacionparcial',
            index=models.Index(fields=['parcial', 'quimestre'], name='classes_cal_parcial_700fb2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calificacionparcial',
            unique_together={('student', 'subject', 'parcial', 'quimestre', 'tipo_aporte')},
        ),
    ]
