# Generated by Django 5.2.9 on 2025-12-20 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradelevel',
            name='docente_tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutored_grade_levels', to='teachers.teacher', verbose_name='Docente Tutor'),
        ),
    ]
