# Generated by Django 5.2.9 on 2025-12-20 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_remove_gradelevel_docente_tutor_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradelevel',
            name='docente_tutor',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutored_grade_levels', to='users.usuario', verbose_name='Docente Tutor'),
        ),
    ]
