# Generated by Django 5.2.14 on 2026-06-02 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_alter_clase_ciclo_lectivo'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradelevel',
            options={'ordering': ['level', 'section'], 'verbose_name': 'Nivel / Paralelo', 'verbose_name_plural': 'Niveles / Paralelos'},
        ),
        migrations.AddField(
            model_name='gradelevel',
            name='ciclo',
            field=models.CharField(blank=True, choices=[('BASICA', 'Básica'), ('MEDIA', 'Media'), ('SUPERIOR', 'Superior'), ('BACHILLERATO', 'Bachillerato')], help_text='Se calcula automáticamente del nivel si se deja en blanco.', max_length=20, verbose_name='Ciclo'),
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='level',
            field=models.CharField(choices=[('1', 'Básica 1'), ('2', 'Básica 2'), ('3', 'Media 3'), ('4', 'Media 4'), ('5', 'Media 5'), ('6', 'Superior 6'), ('7', 'Superior 7'), ('8', 'Superior 8'), ('9', 'Bachillerato 9'), ('10', 'Bachillerato 10'), ('11', 'Bachillerato 11')], max_length=20, verbose_name='Nivel'),
        ),
        migrations.CreateModel(
            name='MallaCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligatoria', models.BooleanField(default=True, help_text='Si es obligatoria se inscribe automáticamente al asignar el nivel.', verbose_name='Obligatoria')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de visualización dentro del nivel.', verbose_name='Orden')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='malla_curricular', to='classes.gradelevel', verbose_name='Nivel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='malla_entries', to='subjects.subject', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Entrada de Malla Curricular',
                'verbose_name_plural': 'Malla Curricular',
                'ordering': ['nivel__level', 'orden', 'subject__name'],
                'unique_together': {('nivel', 'subject')},
            },
        ),
    ]
