# Generated by Django 5.2.15 on 2026-06-30 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_add_ciclo_grade_level_and_malla_curricular'),
        ('students', '0004_student_representante_usuario'),
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
        ('users', '0002_alter_usuario_rol_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='JustificacionAusencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='justificaciones/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('comentario_revision', models.TextField(blank=True)),
                ('asistencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='justificacion', to='classes.asistencia')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificaciones_revisadas', to='users.usuario')),
            ],
            options={
                'verbose_name': 'Justificación de Ausencia',
                'verbose_name_plural': 'Justificaciones de Ausencia',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='Recuperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SUPLETORIO', 'Supletorio'), ('REMEDIAL', 'Remedial'), ('GRACIA', 'De Gracia')], default='SUPLETORIO', max_length=15)),
                ('quimestre', models.CharField(choices=[('Q1', 'Quimestre 1'), ('Q2', 'Quimestre 2')], default='Q1', max_length=2)),
                ('fecha', models.DateField()),
                ('nota_original', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('nota_recuperacion', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('REPROBADA', 'Reprobada')], default='PENDIENTE', max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recuperaciones', to='classes.clase')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recuperaciones', to='students.student')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recuperaciones_registradas', to='teachers.teacher')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recuperaciones', to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Recuperación',
                'verbose_name_plural': 'Recuperaciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
